# Form implementation generated from reading ui file '/home/jason/scriptura/src/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebarDrawer = QtWidgets.QWidget(parent=self.centralwidget)
        self.sidebarDrawer.setMinimumWidth(48)
        self.sidebarDrawer.setMaximumWidth(320)
        self.sidebarDrawer.setObjectName("sidebarDrawer")
        self.sidebarDrawerLayout = QtWidgets.QVBoxLayout(self.sidebarDrawer)
        self.sidebarDrawerLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarDrawerLayout.setSpacing(0)
        self.sidebarDrawerLayout.setObjectName("sidebarDrawerLayout")
        self.fileTreeView = QtWidgets.QTreeView(parent=self.sidebarDrawer)
        self.fileTreeView.setObjectName("fileTreeView")
        self.sidebarDrawerLayout.addWidget(self.fileTreeView)
        self.horizontalLayout.addWidget(self.sidebarDrawer)
        self.editorContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.editorContainer.setObjectName("editorContainer")
        self.editorContainerLayout = QtWidgets.QVBoxLayout(self.editorContainer)
        self.editorContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.editorContainerLayout.setSpacing(0)
        self.editorContainerLayout.setObjectName("editorContainerLayout")
        self.topToolbar = QtWidgets.QWidget(parent=self.editorContainer)
        self.topToolbar.setMinimumHeight(44)
        self.topToolbar.setMaximumHeight(44)
        self.topToolbar.setObjectName("topToolbar")
        self.topToolbarLayout = QtWidgets.QHBoxLayout(self.topToolbar)
        self.topToolbarLayout.setContentsMargins(8, 4, 8, 4)
        self.topToolbarLayout.setSpacing(6)
        self.topToolbarLayout.setObjectName("topToolbarLayout")
        self.editorContainerLayout.addWidget(self.topToolbar)
